tree_progress/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',  include('users.urls')),
    path('', include('trees.urls')),
]

trees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'trees'
urlpatterns = [
    # path('', views.index, name='index'),              # function-based view
    path('', views.Index.as_view(), name='index'),      # Class-based view
    path('all_entries/', views.AllEntries.as_view(), name='all_entries'),             
    path('entry/<int:pk>/', views.EntryView.as_view(), name='entry'),             
    path('entry/<int:pk>/remove', views.TreeDeleteEntry.as_view(), name='delete_entry'),
    path('entry/edit/<int:pk>', views.TreeEditEntry.as_view(), name='edit_entry'),
    path('image_album/<int:pk>/remove', views.TreeDeleteImageAlbum.as_view(), name='delete_image_album'),
    path('new_tree/', views.NewTree.as_view(), name='new_tree'),
    # path('user_trees/<', views.UserTrees.as_view(), name='user_trees'),
    path('user_trees/<int:pk>/', views.UserTrees.as_view(), name='user_trees'),

    path('tree/<int:pk>/', views.TreeView.as_view(), name='tree'),  # old
    path('tree/<int:pk>/edit_tree', views.EditTree.as_view(), name='edit_tree'),
    path('tree/<int:pk>/delete_tree', views.DeleteTree.as_view(), name='delete_tree'),
    # path('tree/<int:pk>/', views.TreeDislpayEntries.as_view(), name='tree'),   # new

    # path('tree/<int:tree_id>/', views.tree, name='tree'),
    # path('new_entry/', views.new_entry, name='new_entry'),
    # path('entry/<int:entry_id>/', views.entry, name='entry'),

    path('new_test_tree/', views.NewTestTree.as_view(), name='new_test_tree'),
    # temporary, test:
    # path('signup/', views.SignUpView.as_view(), name='signup'),

]

if settings.DEBUG:          # if not needed?
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

trees/models.py
from email.policy import default
import uuid
import pathlib

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from tools import *

def user_directory_path(instance, filename):                  # do usunięcia albo przerobienia
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'images/user_{instance.entry.tree.owner.id}/{filename}'

def tree_images_upload_handler(instance, filename):             # later: make it better
    fpath = pathlib.Path(filename)
    new_fname = str(uuid.uuid1())   # uuid1 -> uuid + timestamp
    return f'images/user_{instance.owner.id}/{new_fname}{fpath.suffix}'

def album_path_handler(instance, filename):                 # do usunięcia albo przerobienia
    return f'images/album_{instance.album.id}/{filename}'


class Tree(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    specie = models.CharField(max_length=50, blank=True)
    specie_latin = models.CharField(max_length=50, blank=True)
    description = models.TextField(max_length=1000, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    # date_planted = models.DateField(blank=True)                   #?
    image = models.ImageField(upload_to=tree_images_upload_handler, blank=True)    # later: upload photo or choose among images assigned do entries
    is_bonsai = models.BooleanField(default=False)
    
    # rating = models.FloatField()
    # tags: bonsai, decidous, conifer, indoor, outdoor
    # location = models.CharField(max_length=200)
    # height = models.IntegerField()
    # diameter = models.IntegerField()

    def __str__(self):
        return self.name
    
class ImageAlbum(models.Model):     #ImageAlbum powinien być przypięty do Entry a nie odwrotnie?
    def default(self):
        return self.images.filter(default=True).first()

    def show_images(self):
        return self.images.all()
    
    # def thumbnails(self):
    #     return self.images.filter(width__lt=100, length_lt=100)

class Image(models.Model):
    album = models.ForeignKey(ImageAlbum, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=album_path_handler, blank=True)
    default = models.BooleanField(default=False)    


class Entry(models.Model):
    tree = models.ForeignKey(Tree, on_delete=models.CASCADE)
    album = models.OneToOneField(ImageAlbum, on_delete=models.CASCADE, related_name='entry', blank=True, null=True)
    # owner = models.ForeignKey(User, on_delete=models.CASCADE)   # settings.AUTH_USER_MODEL instead of User?
    date_added = models.DateTimeField(auto_now_add=True)
    date_photos_taken = models.DateField()
    comment = models.TextField(max_length=1000, blank=True, null=True)
    # image = models.ImageField(upload_to=tree_images_upload_handler, blank=True)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        date = str(self.date_photos_taken.strftime('%Y-%m-%d')) if self.date_photos_taken else ''
        return f'{self.tree.name}: ' + date



# def get_image_filename(filename):   
#     # slug = slugify()
#     return f"post_images/{filename}"

trees/forms.py
from django import forms
from .models import Tree, Entry, ImageAlbum, Image 
from bootstrap_modal_forms.forms import BSModalModelForm

from tools import lol

class TestTreeForm(BSModalModelForm):
    class Meta:
        model = Tree
        fields = ['name', 'specie', 'specie_latin', 'description', 'is_bonsai', 'image']


class TreeForm(forms.ModelForm):
    class Meta:
        pass
        model = Tree
        fields = ['name', 'specie', 'specie_latin', 'description', 'is_bonsai', 'image']


class EntryForm(forms.ModelForm):
    """ Comment and date_photos_taken defined here, because of FullEntryForm """
    comment = forms.CharField(label="Comment", required=False)
    date_photos_taken = forms.DateField(label="Date photos taken", widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Entry
        fields = ['comment', 'date_photos_taken']

    def __init__(self, *args, **kwargs):
        """ Save the request with the form so it can be accessed in clean_*() """
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)


class FullEntryForm(EntryForm):
    pass
    # Jeśli wyskakuje błąd, to może być kwestia braku zdefiniowania odpowiedniego albumu
    # ImageForm zamiast fileField?
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        # model = ImageAlbum   # tego nie było / old
        model = Image   # new
        fields = EntryForm.Meta.fields + ['images',]



# TEMPORARY

# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


# class CustomUserCreationForm(CreateUpdateAjaxMixin, PopRequestMixin, UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'password1', 'password2']

trees/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import FormView
from django.views.generic import DeleteView, UpdateView
from django.views import View
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
##
# from django.forms import modelformset_factory
# from django.contrib.auth.decorators import login_required
# from django.contrib import messages
# from django.http import HttpResponseRedirect
# from .forms import TreeForm, EntryForm, ImageForm
##
from .models import Tree, Entry, Image, ImageAlbum
from .forms import TreeForm, EntryForm, FullEntryForm, TestTreeForm

from bootstrap_modal_forms.generic import BSModalCreateView
from tools import *


class Index(ListView):
    model = Tree
    template_name = 'trees/index.html'
    context_object_name = 'trees'   # default: object_list

    def get_queryset(self, *args, **kwargs):
        qs = super(Index, self).get_queryset(*args, **kwargs)
        qs = qs.order_by('-date_added')
        return qs
        

class UserTrees(ListView):
    model = Tree
    template_name = 'trees/user_trees.html'
    context_object_name = 'user_trees'

    def get_queryset(self, *args, **kwargs):
        qs = super(UserTrees, self).get_queryset(*args, **kwargs)
        qs = qs.filter(owner_id=self.kwargs['pk'])
        qs = qs.order_by('-date_added')
        # qs = qs.filter(user=self.request.user)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['owner_id'] = self.kwargs['pk']
        context['owner_name'] = User.objects.get(pk=self.kwargs['pk'])
        return context


class AllEntries(ListView):
    model = Entry
    template_name = 'trees/all_entries.html'
    context_object_name = 'all_entries'   

    def get_queryset(self, *args, **kwargs):
        qs = super(AllEntries, self).get_queryset(*args, **kwargs)
        qs = qs.order_by('-date_added')
        return qs


class TreeDislpayEntries(ListView):
    model = Entry
    template_name = 'trees/tree.html'
    context_object_name = 'tree_entries'
    
    def get_queryset(self, *args, **kwargs):
        # lol('▬▬▬ GET QUERYSET ▬▬▬')
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tree_id=self.kwargs['pk'])
        qs = qs.order_by('-date_photos_taken', '-album_id')
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tree'] = Tree.objects.get(pk=self.kwargs['pk'])   # zamiast tego można coś w stylu post.title w templacie
        # context['form'] = EntryForm()   # Old
        context['form'] = FullEntryForm()   # New
        return context

class TreeAddEntry(SingleObjectMixin, FormView):
    model = Tree
    form_class = EntryForm  # Old
    # form_class = FullEntryForm  # New; z tym nie działa - komunikat, "field is required" (mimo że wybrano)
    template_name = 'trees/tree.html'

    # problem: jeśli invalid, to wyświetla template ale bez entries

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()     # Tree object
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form): 
        entry = form.save(commit=False)
        entry.album = ImageAlbum.objects.create()
        entry.tree = self.object
        # lol(entry.__dict__)
        entry.save()

        files = self.request.FILES.getlist('images')
        default = True
        for file in files:
            Image.objects.create(album=entry.album, image=file, default=default)
            default = False
        return super().form_valid(form)

    def get_success_url(self):
        tree = self.get_object()
        return reverse('trees:tree', kwargs={'pk': tree.pk})


class TreeEditEntry(OwnerRequirementMixin, UpdateView):
    model = Entry
    form_class = EntryForm
    template_name = 'trees/edit_entry.html'

    def get_success_url(self):
        tree = self.object.tree
        return reverse('trees:tree', kwargs={'pk': tree.pk})

    
class TreeDeleteEntry(OwnerRequirementMixin, DeleteView):  # Add mixin to delete entry directly from a tree page
    model = Entry
    template_name = 'trees/delete_entry.html'  

    def get_success_url(self):
        tree = self.object.tree
        return reverse('trees:tree', kwargs={'pk': tree.pk})


class TreeDeleteImageAlbum(DeleteView):  # Add mixin to delete entry directly from a tree page
    model = ImageAlbum
    template_name = 'trees/delete_image_album.html'  

    # ! doesn't get the tree object
    def get_success_url(self):
        tree = ImageAlbum.objects.get(pk=self.object.pk)
        return reverse('trees:tree', kwargs={'pk': tree.pk})


class TreeView(View):

    def get(self, request, *args, **kwargs):
        # lol('get')
        view = TreeDislpayEntries.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = TreeAddEntry.as_view()
        return view(request, *args, **kwargs)


class EntryView(DetailView):
    model = Entry
    template_name = 'trees/entry.html'
    context_object_name = 'entry'

@method_decorator(login_required, name='dispatch')
class NewTree(FormView):
    form_class = TreeForm
    template_name = 'trees/new_tree.html'

    def get_success_url(self) -> str:
        return reverse('trees:tree', kwargs={'pk': self.new_tree.pk})

    def form_valid(self, form):
        lol('NewTree')
        self.new_tree = form.save(commit=False)
        self.new_tree.owner = self.request.user
        self.new_tree.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class NewTestTree(BSModalCreateView):
# class NewTestTree(FormView):
    template_name = 'trees/new_test_tree.html'
    form_class = TestTreeForm
    success_message = 'Success Tree was created.'

    def get_success_url(self) -> str:
        return reverse_lazy('trees:tree', kwargs={'pk': self.new_tree.pk})

    def form_valid(self, form):
        lol('New Test Tree')
        self.new_tree = form.save(commit=False)
        self.new_tree.owner = self.request.user
        self.new_tree.save()
        return super().form_valid(form)


    

@method_decorator(login_required, name='dispatch')
class EditTree(OwnerRequirementMixin, UpdateView):
    model = Tree
    form_class = TreeForm
    template_name = 'trees/edit_tree.html'

    def get_success_url(self) -> str:
        return reverse('trees:tree', kwargs={'pk': self.object.pk})


@method_decorator(login_required, name='dispatch')
class DeleteTree(OwnerRequirementMixin, DeleteView):
    model = Tree
    template_name = 'trees/delete_tree.html'
    success_url = reverse_lazy('trees:index')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tree'] = self.get_object()
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

# TEMPORARY

# from django.contrib.messages.views import SuccessMessageMixin
# from django.urls import reverse_lazy
# from django.views import generic
# from bootstrap_modal_forms.mixins import PassRequestMixin
# from .forms import CustomUserCreationForm

# class SignUpView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
#     form_class = CustomUserCreationForm
#     template_name = 'trees/modals/test_signup.html'
#     success_message = 'Success: Sign up succeeded. You can now Log in.'
#     success_url = reverse_lazy('index')








# @login_required
# def new_entry(request):
#     if request.method == 'POST':
#         # Images  will be in request.FILES
#         form = EntryFullForm(request.POST or None, request.FILES or None)
#         files = request.FILES.getlist('images')
#         if form.is_valid():











# @login_required
# def entry(request):

#     ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=3)
#     if request.method == 'POST':
#         entry_form = EntryForm(request.POST)      
#         formset = ImageFormSet(request.POST, request.FILES, queryset=Images.objects.none())
#         if entry_form.is_valid() and formset.is_valid():
#             new_entry = entry_form.save(commit=False)   # commit=False -> don't save yet
#             new_entry.owner = request.user
#             # Add Tree here?
#             new_entry.save

#             for form in formset.cleaned_data:
#                 # this helps to not crash if the user do not upload all the photos
#                 if form:       
#                     image = form['image']
#                     photo = Images(post=new_entry, image=image)
#                     photo.save()
#             # use django messages framework
#             messages.success(request, 'Your entry has been created!')
#             return HttpResponseRedirect("/")
#         else:
#             print(entry_form.errors, formset.errors)
#     else:
#         entry_form = EntryForm()
#         formset = ImageFormSet(queryset=Images.objects.none())
#     return render(request, 'index.html', {'form': entry_form, 'formset': formset})    

trees/templates/trees/all_entries.html
{% extends "trees/base.html" %}
{% block page_header %} <!-- # tag with "content" name -->
    <div>
        <h1>All entries</h1>
    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <ul>
            {% for entry in all_entries %}
                <li>
                    <a href="{% url 'trees:entry' entry.pk %}">
                        <h4>{{ entry }}</h4>
                        
                        <!-- {% if tree.image %}
                            <img src="{{ tree.image.url }}" alt="{{ tree.name }}" width="200" zheight="200">
                            {% endif %} -->
                            
                    </a>
                    <p>id: {{ entry.id }}</p>
                    <p>name: {{ entry.tree }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

trees/templates/trees/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        {% include "trees/base/css.html" %}
        
    <title>Hello, world!</title>
</head>
  <body>
      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
          <a class="navbar-brand" href="{% url 'trees:index' %}">Tree Progression</a>
          
          
          
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="{% url 'trees:all_entries' %}" class="nav-link">All entries</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="navbar-text mx-2"><span class="navbar-text">Hello, {{ user.username }}.</span></li>
                    <li class="nav-item"><a href="{% url 'trees:user_trees' user.pk %}" class="nav-link">My trees</a></li>
                    <li class="nav-item"><a href="{% url 'users:logout' %}" class="nav-link">Log out</a></li>
                    
                {% else %}
                <li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link">Sign up</a></li>
                <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link">Log in</a></li>
                {% endif %}
                
            </ul>
            
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

    {% include 'trees/base/js.html' %}
</body>
</html>

trees/templates/trees/delete_entry.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h2>Delete entry from  {{entry.date_photos_taken}}</h2>
        <!-- {{ request }} -->

    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <form action="{% url 'trees:delete_entry' entry.pk %}" method="post">
            {% csrf_token %}
            <strong>Are you sure?</strong>
            <button name="submit">Delete entry!</button>
        </form>

    </div>
{% endblock content %}

trees/templates/trees/delete_image_album.html
{% comment %}
Redundant and can be deleted?
{% endcomment %}


{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h2>Delete album  number {{ imagealbum.id }}</h2>
        {{ request }}

    </div>
        
    {% endblock page_header %}  

{% block content %}
    <p>tree number: {{ imagealbum.tree_id }} </p>
    <div>
        <form action="{% url 'trees:delete_image_album' imagealbum.id %}" method="post">
            {% csrf_token %}
            <strong>Are you sure?</strong>
            <button name="submit">Delete album!</button>
        </form> 

    </div>
{% endblock content %}

trees/templates/trees/delete_tree.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h2>Delete tree {{ tree }}?</h2>
        <!-- {{ request }} -->

    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <form action="{% url 'trees:delete_tree' tree.pk %}" method="post">
            {% csrf_token %}
            <strong>Are you sure?</strong>
            <button name="submit">Delete tree!</button>
        </form>

    </div>
{% endblock content %}

trees/templates/trees/edit_entry.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h2>Edit entry:  {{entry.date_photos_taken}}</h2>
        <!-- {{ request }} -->

    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <form action="{% url 'trees:edit_entry' entry.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <strong>Are you sure?</strong>
            <button name="submit">Save entry</button>
        </form>
        <hr>
        <h2>ADD FUNCTION TO DELETE AND UPLOAD NEW PHOTOS</h2>
        <h3>(After changing database structyre)</h3>

    </div>
{% endblock content %}

trees/templates/trees/edit_tree.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h2>Edit tree:  {{entry.date_photos_taken}}</h2>
        <!-- {{ request }} -->

    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <form action="{% url 'trees:edit_tree' tree.pk %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <strong>Are you sure?</strong>
            <button name="submit">Save tree</button>
        </form>
        <hr>
        <h2>do something with the main photo?</h2>

    </div>
{% endblock content %}

trees/templates/trees/index.html
{% extends "trees/base.html" %}
{% block page_header %} <!-- # tag with "content" name -->
    <div class="jumbotron">
        <h1>Track your tree progression.</h1>
        
    </div>
        
    {% endblock page_header %}  

{% block content %}
    {% comment %}
    {% endcomment %}
    {% include "trees/modals/test_modal.html" %}
    <hr>
    




    <div>
        <p>Here will be a list with thumbnails of all trees of all users (which contain main image)</p>
        {% if user.is_authenticated %}
            <a href="{% url 'trees:new_tree' %}"> Add tree </a>
        {% endif %}


        <ul>
            {% for tree in trees %}
                {% if tree.image %}
                    <li>
                        <a href="{% url 'trees:tree' tree.pk %}">
                        <h4>{{ tree.name }}</h4>
                            <img src="{{ tree.image.url }}" alt="{{ tree.name }}" width="200" zheight="200">
                        </a>
                        <p><a href="{% url 'trees:user_trees' tree.owner.pk %}">{{ tree.owner }}</a></p>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

trees/templates/trees/new_tree.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h1>New tree form</h1>
    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <form action="{% url 'trees:new_tree' %}" enctype="multipart/form-data" method="post" >
            {% csrf_token %}
            {{ form.as_p }}
            <!-- <input type="submit" value="Create tree"> -->
            <button name="submit">Add tree</button>
        </form>

    </div>
{% endblock content %}

trees/templates/trees/tree.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h1>{{ tree }} </h1>
        {% if tree.owner == request.user %}
            <small>
                <a href="{% url 'trees:edit_tree' tree.pk %}">(Edit tree)</a>
                <a href="{% url 'trees:delete_tree' tree.pk %}">(Delete tree)</a>
            </small>
        {% endif %}
    </div>
    
    {% endblock page_header %}  
    
    {% block content %}
    <div>
        <div>
            <p>name: {{ tree }} </p>
            <p>owner: {{ tree.owner }} </p>
            <p>specie: {{ tree.specie }} 
                {% if tree.specie_latin %}
                <span class="font-italic">({{ tree.specie_latin}})</span> </p>
                {% endif %}
            {% if tree.date_planted %}
            <p>date planted: {{ tree.date_planted }} </p>
            {% endif %}
            {% if tree.description %}
                <p>description: {{ tree.description }} </p>
            {% endif %}
            <hr>
        </div>
        <div>
            <h2>Default photo</h2>
            {% if tree.image %}
            <img src="{{ tree.image.url }}" alt="{{ tree.image.name }}" class="img-fluid">
            {% else %}
            <p>No default photo</p>
            {% endif %}
            <hr>
        </div>
            
        
       
        <h3>Update tree with new photos!</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Submit</button>
        </form>
        
        <hr>
        <h3>Photos / entries / updates / checkpoints / milestones...:</h3>
        <ul>
            {% for entry in tree_entries %}
                <li>
                    <a href="{% url 'trees:entry' entry.pk %}"> <h4>{{ entry }}</h4> </a>
                    {% if tree.owner == request.user %}
                        <small>
                            <a href="{% url 'trees:edit_entry' entry.pk %}">(Edit entry)</a>
                            <a href="{% url 'trees:delete_entry' entry.pk %}">(Delete entry)</a>
                            <!-- <a href="{% url 'trees:delete_image_album' entry.album.id %}">(Delete album)</a> -->
                        </small>
                    {% endif %}
                    <br>
                    
                    {% if entry.album.default %}
                        <a href="{% url 'trees:entry' entry.pk %}">
                            <img src="{{ entry.album.default.image.url }}" alt="{{ entry.album.default.image.name }}" width="300" zheight="200">
                        </a>
                    {% endif %}
                        
                        <!-- {% if tree.image %}
                            <img src="{{ tree.image.url }}" alt="{{ tree.name }}" width="200" zheight="200">
                            {% endif %} -->
                            
                    {# <!-- <p>{% url 'trees:entry' album.pk %} </p> --> #}
                    <p class="lead">comment: {{ entry.comment }}</p>
                    <small  class="text-muted">
                        <p>entry id: {{ entry.id }}</p>
                        <p>name: {{ entry.tree }}</p>
                        <p>album: {{ entry.album }}</p>
                        <p>album id: {{ entry.album.id }}</p>
                    </small>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

trees/templates/trees/user_trees.html
{% extends "trees/base.html" %}
{% block page_header %}
    <div>
        <h1>Trees added by  {{ owner_name }} (user id: {{ owner_id }})</h1>
    </div>
        
    {% endblock page_header %}  

{% block content %}
    <div>
        <ul>
            {% for tree in user_trees %}
                <li>
                    <a href="{% url 'trees:tree' tree.pk %}">
                        <h4>{{ tree.name }}</h4>
                        {% if tree.image %}
                            <img src="{{ tree.image.url }}" alt="{{ tree.name }}" width="200" zheight="200">
                        {% endif %}
                    </a>
                    <p><a href="{% url 'trees:user_trees' tree.owner.pk %}">{{ tree.owner }}</a></p>
                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock content %}